### ISSUE TITLE
Markdown table rows extend beyond scrollable area in edit mode

### ISSUE THREAD

**Issue by daneah** [Slowbad/obsidian-solarized#14]
**Note**: this appears to be an issue with the default styles as well, but could be nice to provide a fix for in this theme.

When creating a Markdown table, if a row is longer than the width of the window the last character or so (typically the closing `|`) isn't visible within the scrollable area. After viewing the styles directly in the app, overriding the following rule gives it enough padding to be able to scroll to the `|` and see the cursor after it as well:

```css
.cm-s-obsidian .HyperMD-table-row > :last-child {
    padding-right: 48px !important;  /* default is 22px !important */
}
```
