### ISSUE TITLE
Dark theme is not consistent

### ISSUE THREAD

**Issue by marchank0** [Slowbad/obsidian-solarized#21]
All text inputs in dark theme have light theme background on mouseover

Need to fix css property (possibly to --base03)
```css
.theme-dark {
    ...
    --background-modifier-form-field-highlighted: var(--base3);
    ...
}
```
I'm not sure which color should be used according to solarized color theme. 
If someone provides the color, I will make a pull request

<img width="821" alt="solar-dark-bug-Screenshot at Feb 09 17-08-02" src="https://user-images.githubusercontent.com/1183579/153219039-ba39dec5-bcfa-4e44-9d4a-14b236ba3b1d.png">
