### ISSUE TITLE
This theme does not respect the font setting of Obsidian?

### ISSUE THREAD

**Issue by ghost** [Slowbad/obsidian-solarized#32]
I found two problems with the `Appearance`-`Font` settings.
I don't know if Obsidian or this theme is causing these two problems, but I did encounter problems only when using this theme，and other themes are normal.

1. After changing the `Font size` setting, the font size of the application interface changes, but the font size of the file content does not change.

2. Enable the `Quick font size adjustment` function then use it, and find that the font size of both the application interface and the file content has not changed.

Platform: Windows 11
Obsidian version: 1.3.5
Plugin version: 1.0.5-beta

**Comment by berezovskyi** [comment]
Same here, I found that the Solarized theme tries to use a monospace font everywhere, which is messing with my stylesheet adjustments to the default theme. I would love if there was a possibility/resources to release a version of the theme that only introduced the solarized colors without making any other style changes. 

---

If anyone is interested, here is my Solarized stylesheet (based off http://www.zovirl.com/2011/07/22/solarized_cheat_sheet/) for the default theme instead:

```css
:root .theme-light {
   --background-primary: #fdf6e3;
   --background-secondary: #eee8d5;
   --background-secondary-alt: #eee8d5;
   --color-base-00: #fdf6e3;
   --color-base-05: #fdf6e3;
   --color-base-10: #fdf6e3;
   --color-base-20: #eee8d5;
   --color-base-25: #eee8d5;
   --color-base-30: #93a1a1;
   --color-base-35: #93a1a1;
   --color-base-40: #839496;
   --color-base-50: #657b83;
   --color-base-60: #586e75;
   --color-base-70: #073642;
   --color-base-100: #002b36;
 }


 :root .theme-dark {
   --background-primary: #002b36;
   --background-secondary: #073642;
   --background-secondary-alt: #073642;
   --color-base-00: #002b36;
   --color-base-05: #002b36;
   --color-base-10: #073642;
   --color-base-20: #073642;
   --color-base-25: hsl(194, 14%, 30%);
   --color-base-30: #586e75;
   --color-base-35: #657b83;
   --color-base-40: #839496;
   --color-base-50: var(--text-accent);
   --color-base-60: #93a1a1;
   --color-base-70: #93a1a1;
   --color-base-100: #839496;
 }
```
