### ISSUE TITLE
Highlighted text is not consistent on the note page and within community plugins' search page

### ISSUE THREAD

**Issue by marchank0** [Slowbad/obsidian-solarized#35]
Example:
<img width="809" alt="Screenshot 2023-12-21 at 17 00 19" src="https://github.com/harmtemolder/obsidian-solarized/assets/1183579/ef859994-057e-4d6a-8a23-ffa11659de37">

Expected behaviour:
<img width="802" alt="Screenshot 2023-12-21 at 19 44 01" src="https://github.com/harmtemolder/obsidian-solarized/assets/1183579/cba45290-1ecc-4c4e-a906-f623f7aeaa14">
<img width="593" alt="Screenshot 2023-12-21 at 19 45 55" src="https://github.com/harmtemolder/obsidian-solarized/assets/1183579/61016095-f56b-495f-bdd1-3c9b54df886b">

Possible fix:
```css
/* Preview highlights*/
.markdown-preview-section mark {
  color: var(--text-on-accent)
}
/* Communitiy plugins' search highlights*/
.community-modal-search-results-wrapper span.suggestion-highlight {
  color: var(--text-on-accent)
}
```
